export const testCase = {
  id: 'INT-022',
  module1: 'Data Export and Audit Trail Module',
  module2: 'View Performance Module',
  process:
    'Test integration when exported tables include data generated by player and admin system activity.',
  precondition:
    'Users, sessions, achievements, and user achievements contain existing records.',
  expectedResult: 'Selected tables export in PDF, CSV, or JSON format with current data included.',
}

export function verifySpecification() {
  return (
    testCase.precondition.includes('sessions') &&
    testCase.expectedResult.includes('PDF, CSV, or JSON')
  )
}

export default testCase
